const items = [
    {
        id: '001',
        image: '1.jpg',
        company: 'Carlton London',
        item_name: 'Rhodium-Plated CZ Floral Studs',
        original_price: 1045,
        current_price: 606,
        discount_percentage: 42,
        return_period: 14,
        delivery_date: '10 Oct 2023',
        rating: {
            stars: 4.5,
            count: 1400,
        },
    },
    {
        id: '002',
        image: '2.jpg',
        width:'260',
        height:'310',
        company: 'REDTAPE',
        item_name: 'Men shoes',
        original_price: 2599,
        current_price: 1800,
        discount_percentage: 42,
        return_period: 14,
        delivery_date: '10 Oct 2023',
        rating: {
            stars: 4.3,
            count: 24,
        },
    },
    {
        id: '003',
        image: '3.jpg',
        width:'260',
        height:'310',
        company: 'iPhone 15 pro',
        item_name: 'smartPhone',
        original_price: 150000,
        current_price: 80000,
        discount_percentage: 59,
        return_period: 14,
        delivery_date: '10 Oct 2023',
        rating: {
            stars: 4.1,
            count: 249,
        },
    },
    {
        id: '004',
        image: '4.jpg',
        company: 'Titan ',
         width:'260',
        height:'310',
        item_name: 'Titan heritage watch',
        original_price: 999,
        current_price: 999,
        discount_percentage: 0,
        return_period: 14,
        delivery_date: '10 Oct 2023',
        rating: {
            stars: 5.0,
            count: 10,
        },
    },
    {
        id: '005',
        image: '5.jpg',
        company: 'Sportz',
        item_name: 'motivational water bottle',
        original_price: 1399,
        current_price: 489,
        discount_percentage: 65,
        return_period: 14,
        delivery_date: '10 Oct 2023',
        rating: {
            stars: 4.2,
            count: 3500,
        },
    },
    {
        id: '006',
        image: '6.jpg',
        company: 'Sencor',
        item_name: 'smart television',
        original_price: 14995,
        current_price: 14995,
        discount_percentage: 0,
        return_period: 14,
        delivery_date: '10 Oct 2023',
        rating: {
            stars: 0.0,
            count: 0,
        },
    },
    {
        id: '007',
        image: '7.jpg',
         width:'260',
        height:'260',
        company: 'YAYAWAR',
        item_name: 'girls dress',
        original_price: 1599,
        current_price: 639,
        discount_percentage: 60,
        rating: {
            stars: 4.2,
            count: 388,
        },
    },
    {
        id: '008',
        image: '8.jpg',
        company: 'HP HeadPhone',
        item_name: 'headphones with mic',
        original_price: 4000,
        current_price: 1499,
        discount_percentage: 50,
        return_period: 14,
        delivery_date: '10 Oct 2023',
        rating: {
            stars: 4.2,
            count: 5200,
        },
    }
    ,
     {
        id: '009',
        image: '9.jpg',
        company: 'MackBook',
        item_name: 'LAPTOP',
        original_price: 115000,
        current_price: 74999,
        discount_percentage: 50,
        return_period: 14,
        delivery_date: '10 Oct 2023',
        rating: {
            stars: 4.8,
            count: 3500,
        },
    }
    ,
     {
        id: '010',
        image: '10.jpg',
        company: 'makesoft',
        item_name: 'Sofaset',
        original_price: 114000,
        current_price: 69999,
        discount_percentage: 50,
        return_period: 14,
        delivery_date: '10 Oct 2023',
        rating: {
            stars: 4.8,
            count: 3500,
        },
    }
];